version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    volumes:
      - /home/amit/tick/influxdb/influxdb-volume:/var/lib/influxdb
    networks:
      - influxdb
  telegraf:
    image: telegraf:latest
    hostname: telegraf
    container_name: telegraf
    volumes:
      - /home/amit/tick/telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - influxdb
  chronograf:
    ports:
      - 8888:8888
    networks:
      - influxdb
    image: chronograf
    command: --influxdb-url=http://influxdb:8086
    depends_on:
      influxdb:
        condition: service_started
      telegraf:
        condition: service_started
  kapacitor:
    ports:
      - 9092:9092
    container_name: kapacitor
    volumes:
      - /home/amit/tick/kapacitor/kapacitor-data/etc:/var/lib/kapacitor
      - /home/amit/tick/kapacitor/kapacitor-data/etc/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    networks:
      - influxdb
    environment:
      - KAPACITOR_AS_ROOT=true
    image: kapacitor
    hostname: kapacitor
    depends_on:
      influxdb:
        condition: service_started
      chronograf:
        condition: service_started
networks:
  influxdb:
    external: true
